#!/bin/bash

# mffuf_vhost: Virtual host enumeration using ffuf
if [ -z "$1" ]; then
    echo "Usage: $0 <target>"
    exit 1
fi

ffuf-vhost()
{
    arg_count=3;
    if [[ -n $2 && $2 != -* ]]; then
        wordlist=$2
    else
        wordlist='/usr/share/seclists/Discovery/DNS/subdomains-top1million-110000.txt';
        arg_count=2;
    fi;
    ffuf -c -H 'Host: FUZZ.$1' -u http://$1 -w $wordlist ${@: $arg_count}
}

ffuf-vhost()
